server:
  port: 10086 # 服务端口
spring:
  application:
    name: eureka-server # eureka的服务名称
eureka:
  instance:
    # eureka服务端的名称
    hostname: localhost
  client:
    register-with-eureka: true
    fetch-registry: false
    service-url:  # eureka的地址信息
      defaultZone: http://localhost:10086/eureka
    eureka-connection-idle-timeout-seconds: 10