spring:
  application:
    name: back-system
  datasource:
    url: jdbc:mysql://localhost:3306/elm?useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: zzwzzw
    driver-class-name: com.mysql.cj.jdbc.Driver

server:
  port: 8089

oss:
  accessKey: aBOws0OzW2zNgJq1Yp0h4KG8tc3KFMFX5Ech7Ibs
  secretKey: 20wu4AHg1VVNjPcyVP3-HB-VIgTQSVjScGyjYsZe
  bucket: elm-photo